language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
sudo: required
install: pip install pytest
script: 
  - pyloc=$(which python)
  - sudo $pyloc -m pytest
