language: python

python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- nightly
- pypy
- pypy3
sudo: required
install: pip install pytest
script:
- pyloc=$(which python)
- sudo $pyloc -m pytest
notifications:
  slack:
    secure: OuuwJ9+LpyneMNfdBt+sdNaSyfxMTX9cTOvMPtBqZXYM/9ae5dvP6OzZE9F6pGwnL9hmBA/mLo0HzODFjw3Ofw5IFfwGyvH9EXzUN9FaY/3G08N/uP1wHwKeKSBiE9FJMm7y2vm3fqpQJJgtw3Fmfs7855pKW0d4m60kxLVsjojAmBGodlnAcpP9fapfB+iIPvuk+9L2Tw6LFU+75U7o8uSZidfBGbLSEf+054WfjIq8dMycQTmOK3byRA0gSmkHBD7FWYD4kCdCNRvs1xxBQtvVeKux79/glqi4MztYTpVwgZB5wtlxTRharrhPu81+6v9sKGUrR8lJLDjs3HUph9dL8W8n+lrQmbEDgSMQwgiPu/j+9+Yflzqql6ZbYe9dgre23WmFZGS7qYl6Aydgj89rKzW2TXptxUyiY/YxrYvFtsVZ4lZSauuChCfAZ52t+2BA/3x0jMrqP5HGfFk67vGJpcti2oVK/ZsBs9sF9sLg0bnT/lopoz980kvWqES9qSKVflF2jMiHS7SxgTIml66cuUXMtUpFqtDvKPtDZFxvZC5fIG5c4yTlurL4mnu0E7iQd5GRkaciyZ+u6vxgqjC+0MlnU88xnflltXnwRIhnqR/fEbA+f8FajixSV5trMek4iKwWsOjNAnoZ+sePb2+WhBCwoUCPC3YJw/+e6wQ=
    on_success: always
    on_failure: always
  email: false
