#!/bin/bash

# apt-medium-download <apt-tool> <apt-tool-commands>
#
# Example: apt-medium-download aptitude update
#
# This is only a proof of concept script,
# if you would like to improve something
# please edit apt-medium itself instead.
#

MACHINE_NAMES=`ls ./machine`

for MACHINE_NAME in $MACHINE_NAMES; do
  echo
  echo "Do you want apt-medium-install to later run:"
  echo "  $@ (from the apt-medium at $MACHINE_NAME)"
  echo -n "and download the necessary packages for that machine, now? (y/n)"
  read READ_ANS
  echo
  
  if [ "$READ_ANS" = y ]; then
    export APT_CONFIG="./machine/$MACHINE_NAME/etc/apt/apt-medium.conf-$MACHINE_NAME"
    "$@"
  
    INST_CMD="$1"
    INST_CMD="$INST_CMD --no-d -o dir::etc::status=/var/lib/dpkg/status"
    shift
    if [ "$1" != update ]; then
      INST_CMD="$INST_CMD $@"
      touch ./machine/$MACHINE_NAME/install-commands
      echo "$INST_CMD" >> ./machine/$MACHINE_NAME/install-commands
    fi
  fi

done