name: Apt-Medium

on: [push]

jobs:
  notify_start:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Discord Started
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        details: Starting tests
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
  test: 
    runs-on: ubuntu-latest
    needs: notify_start
    strategy:
        fail-fast: false
        matrix:
            python-version: [2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, pypy-2.7, pypy-3.7, pypy-3.9, pypy-3.10]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pytest
      run: |
        pyloc=$(which python)
        sudo $pyloc -m pip install pytest
    - name: Install Apt-Medium
      run: |
        pyloc=$(which python)
        sudo $pyloc setup.py install
    - name: Apt preparations
      run: |
        sudo add-apt-repository universe
        sudo add-apt-repository multiverse
        sudo add-apt-repository restricted
        sudo apt-get update
        sudo apt-get remove --purge fonts-3270
        sudo apt-get remove --purge fonts-alee
        sudo apt-get remove --purge tshark
        sudo apt-get remove --purge libwireshark*
        sudo apt-get autoremove
    - name: Run tests
      run: |
        pyloc=$(which python)
        sudo $pyloc -m pytest
  notify_result:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
    - name: Notify Discord Result
      uses: SebastiaanZ/github-status-embed-for-discord@main
      with:
        # Discord webhook
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}  # Has to be provided as a string
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

        # Optional arguments for PR-related events
        # Note: There's no harm in including these lines for non-PR
        # events, as non-existing paths in objects will evaluate to
        # `null` silently and the github status embed action will
        # treat them as absent.
        pr_author_login: ${{ github.event.pull_request.user.login }}
        pr_number: ${{ github.event.pull_request.number }}
        pr_title: ${{ github.event.pull_request.title }}
        pr_source: ${{ github.event.pull_request.head.label }}
